name: Build and Release EXE

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze
        pip install -r requirements.txt  

    - name: Build EXE
      run: python setup.py build_exe  # Run the build command for exe

    - name: Zip the build
      run: |
        Compress-Archive -Path build/* -DestinationPath FocusTime.zip

    - name: Upload ZIP as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: FocusTime-Zip
        path: FocusTime.zip

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: FocusTime.zip
        draft: false
        prerelease: false
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
